#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $API_DB_USER WITH ENCRYPTED PASSWORD '$API_DB_PW';
    CREATE DATABASE $API_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $API_DB_NAME TO $API_DB_USER;
EOSQL
