version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '../nginx/vhost.d:/etc/nginx/vhost.d'
      - '../nginx/conf.d:/etc/nginx/conf.d/:rw'
      - '../nginx/certs:/etc/nginx/certs:ro'
      - '../nginx/html:/usr/share/nginx/html'
      - api_static_files:/var/static/api/static

  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - 'nginx-proxy'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '../nginx/vhost.d:/etc/nginx/vhost.d'
      - '../nginx/certs:/etc/nginx/certs:rw'
      - '../nginx/html:/usr/share/nginx/html:rw'
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

  snippets-db:
    restart: always
    image: postgres:10.5
    volumes:
      - snippets_db_data:/var/lib/postgresql/data/
      - ../db/scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ../db/scripts:/scripts:cached
    env_file: prod.env

  snippets-api:
    restart: always
    depends_on:
      - snippets-db
    build: ../snippets-api
    volumes:
      - api_static_files:/code/static
    env_file: prod.env
    environment:
      - VIRTUAL_HOST=snippets-api.dobossy.net
      - SSL_POLICY=AWS-TLS-1-1-2017-01
      - LETSENCRYPT_HOST=snippets-api.dobossy.net

  snippets-client:
    restart: always
    build: ../snippets-client
    environment:
      - VIRTUAL_HOST=snippets.dobossy.net
      - SSL_POLICY=AWS-TLS-1-1-2017-01
      - LETSENCRYPT_HOST=snippets.dobossy.net

volumes:
  snippets_db_data:
  api_static_files:
